"""Add optimized_routes table

Revision ID: 3f1ef5f4b7ac
Revises: f26369c74165
Create Date: 2025-06-13 01:21:15.861721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f1ef5f4b7ac'
down_revision: Union[str, None] = 'f26369c74165'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('optimized_routes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tour_id', sa.UUID(), nullable=True),
    sa.Column('vehicle_id', sa.UUID(), nullable=True),
    sa.Column('route_order', sa.Integer(), nullable=True),
    sa.Column('total_distance_km', sa.Float(), nullable=True),
    sa.Column('total_time_minutes', sa.Integer(), nullable=True),
    sa.Column('efficiency_score', sa.Float(), nullable=True),
    sa.Column('route_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['tour_id'], ['tours.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('optimized_routes')
    # ### end Alembic commands ###
