"""Add created_at and updated_at to tours

Revision ID: db4ab1a42740
Revises: 1d263ab0b3fb
Create Date: 2025-06-16 19:43:49.191956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db4ab1a42740'
down_revision: Union[str, None] = '1d263ab0b3fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tours', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('tours', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tours', 'updated_at')
    op.drop_column('tours', 'created_at')
    # ### end Alembic commands ###
