"""Initial migration

Revision ID: f26369c74165
Revises: 
Create Date: 2025-06-13 00:36:34.017804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f26369c74165'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('hotel_name', sa.String(length=200), nullable=True),
    sa.Column('pickup_lat', sa.Float(), nullable=True),
    sa.Column('pickup_lng', sa.Float(), nullable=True),
    sa.Column('num_adults', sa.Integer(), nullable=True),
    sa.Column('num_children', sa.Integer(), nullable=True),
    sa.Column('preferred_pickup_start', sa.Time(), nullable=True),
    sa.Column('preferred_pickup_end', sa.Time(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('special_requirements', sa.ARRAY(sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tours',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tour_date', sa.Date(), nullable=False),
    sa.Column('activity_type', sa.Enum('snorkeling', 'diving', 'sightseeing', 'kayaking', 'fishing', name='activitytype'), nullable=False),
    sa.Column('destination_name', sa.String(length=200), nullable=True),
    sa.Column('destination_lat', sa.Float(), nullable=True),
    sa.Column('destination_lng', sa.Float(), nullable=True),
    sa.Column('departure_time', sa.Time(), nullable=False),
    sa.Column('status', sa.Enum('planning', 'confirmed', 'in_progress', 'completed', 'cancelled', name='tourstatus'), nullable=True),
    sa.Column('optimization_strategy', sa.String(length=20), nullable=True),
    sa.Column('weather_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('capacity_adults', sa.Integer(), nullable=False),
    sa.Column('capacity_children', sa.Integer(), nullable=False),
    sa.Column('driver_name', sa.String(length=100), nullable=True),
    sa.Column('driver_phone', sa.String(length=20), nullable=True),
    sa.Column('current_lat', sa.Float(), nullable=True),
    sa.Column('current_lng', sa.Float(), nullable=True),
    sa.Column('vehicle_type', sa.Enum('sedan', 'van', 'minibus', name='vehicletype'), nullable=True),
    sa.Column('fuel_type', sa.String(length=20), nullable=True),
    sa.Column('license_plate', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('available', 'in_use', 'maintenance', name='vehiclestatus'), nullable=True),
    sa.Column('equipment', sa.ARRAY(sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tour_participants',
    sa.Column('tour_id', sa.UUID(), nullable=False),
    sa.Column('guest_id', sa.UUID(), nullable=False),
    sa.Column('pickup_order', sa.Integer(), nullable=True),
    sa.Column('actual_pickup_time', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tour_id'], ['tours.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tour_id', 'guest_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tour_participants')
    op.drop_table('vehicles')
    op.drop_table('tours')
    op.drop_table('guests')
    # ### end Alembic commands ###
